# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:39:00+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class BetterAdsStatus(Enum):
    UNKNOWN = 'UNKNOWN'
    PASSING = 'PASSING'
    WARNING = 'WARNING'
    FAILING = 'FAILING'


class FilterStatus(Enum):
    UNKNOWN = 'UNKNOWN'
    ON = 'ON'
    OFF = 'OFF'
    PAUSED = 'PAUSED'
    PENDING = 'PENDING'


class RegionEnum(Enum):
    REGION_UNKNOWN = 'REGION_UNKNOWN'
    REGION_A = 'REGION_A'
    REGION_B = 'REGION_B'
    REGION_C = 'REGION_C'


class PlatformSummary(BaseModel):
    betterAdsStatus: Optional[BetterAdsStatus] = Field(
        None, description="The site's Ad Experience Report status on this platform."
    )
    enforcementTime: Optional[str] = Field(
        None,
        description='The time at which [enforcement](https://support.google.com/webtools/answer/7308033) against the site began or will begin on this platform. Not set when the filter_status is OFF.',
    )
    filterStatus: Optional[FilterStatus] = Field(
        None,
        description="The site's [enforcement status](https://support.google.com/webtools/answer/7308033) on this platform.",
    )
    lastChangeTime: Optional[str] = Field(
        None,
        description="The time at which the site's status last changed on this platform.",
    )
    region: Optional[List[RegionEnum]] = Field(
        None,
        description="The site's regions on this platform. No longer populated, because there is no longer any semantic difference between sites in different regions.",
    )
    reportUrl: Optional[str] = Field(
        None,
        description='A link to the full Ad Experience Report for the site on this platform.. Not set in ViolatingSitesResponse. Note that you must complete the [Search Console verification process](https://support.google.com/webmasters/answer/9008080) for the site before you can access the full report.',
    )
    underReview: Optional[bool] = Field(
        None, description='Whether the site is currently under review on this platform.'
    )


class SiteSummaryResponse(BaseModel):
    desktopSummary: Optional[PlatformSummary] = Field(
        None, description="The site's Ad Experience Report summary on desktop."
    )
    mobileSummary: Optional[PlatformSummary] = Field(
        None, description="The site's Ad Experience Report summary on mobile."
    )
    reviewedSite: Optional[str] = Field(
        None, description='The name of the reviewed site, e.g. `google.com`.'
    )


class ViolatingSitesResponse(BaseModel):
    violatingSites: Optional[List[SiteSummaryResponse]] = Field(
        None, description='The list of violating sites.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'
